apiVersion: v1
kind: Service
metadata:
  name: aiops-bot-service
  namespace: cloudshop
  labels:
    app: aiops-bot
spec:
  type: LoadBalancer
  selector:
    app: aiops-bot
  ports:
    - name: http
      port: 5100
      targetPort: 5100
